### ISSUE TITLE
Script fails to install pants if using asdf (and pyenv?) with system python 3.10

### ISSUE THREAD

**Issue by kamalmarhubi** [pantsbuild/setup#125] opened 2022-07-10 14:41 UTC
If I delete `$XDG_CACHE_DIR/pants`, a directory with a working pants setup stops working. This seems wrong: clearing cache directories should not change behaviour.

Global version is `system` which is 3.10.5:
```
/tmp $ asdf current python
python          system          /home/kamal/.tool-versions
/tmp $ python --version
Python 3.10.5
```

Create a directory with local version 3.9.13:
```
/tmp $ mkdir pants-test
/tmp $ cd pants-test
/t/pants-test $ asdf local python 3.9.13
/t/pants-test $ python --version
Python 3.9.13
```

Follow installation instructions:
```
/t/pants-test $ printf '[GLOBAL]\npants_version = "2.12.0"\n' > pants.toml
/t/pants-test $ curl -sL -O https://static.pantsbuild.org/setup/pants && chmod +x ./pants
/t/pants-test $ ./pants --level=error --version
2.12.0
```

For extra precision, the version of the script corresponds to the current HEAD commit, eb887ad5fd80766214e8c38102a5bc92d1342beb:
```
/t/pants-test $ sha256sum pants
6a1371d1035900c792815e5c7cee6a54c264bd72958f87dba4afec8b60e00cda  pants
/t/pants-test $ curl -sL https://raw.githubusercontent.com/pantsbuild/setup/eb887ad5fd80766214e8c38102a5bc92d1342beb/pants | sha256sum
```
---
**Here's where things go wrong:** I delete the cache directory. I expect the script to reinstall pants and work as before, but instead:
```
/t/pants-test $ rm -r ~/.cache/pants
/t/pants-test $ ./pants --level=error --version
Bootstrapping Pants using /home/kamal/.asdf/shims/python3.9
Creating the virtualenv PEX.
Downloading the Pex PEX.
No python3.9 executable found for python system
SHA256 of https://github.com/pantsbuild/pex/releases/download/v2.1.62/pex is not as expected. Aborting.
```

At least two issues here:
- it doesn't work
- it says the SHA256 doesn't match, but what really happened was it couldn't run [the little hashlib snippet in the script](https://github.com/pantsbuild/setup/blob/eb887ad5fd80766214e8c38102a5bc92d1342beb/pants#L239-L247) because there was no python3.9 available

---

I don't know what the right fix is. Some ideas:
- if .tool-versions or .python-version exist, copy them into the bootstrap directory
  - this is presumptuous because [at least for asdf the file name is a configurable value](https://asdf-vm.com/manage/configuration.html#environment-variables); whatever the fix is, it should not rely on defaults
  - it's also possibly incorrect because those are about project python versions rather than pants' python version
- the script could be less fussy about python versions because it's less smart than the real pants is (unsure if this is an accurate characterisation) 
  - or the script could learn to be as smart as the real pants
- the script could use `sha256sum` instead of python's hashlib (this may break compatibility with some systems; does WSL2 include that binary?)
- pants could run under 3.10; being discussed in https://github.com/pantsbuild/pants/issues/14111
- pants itself should not rely on any installed python; I believe this is slowly being worked on: https://github.com/pantsbuild/pants/issues/7369

**Comment by benjyw** [comment] 2022-07-13 05:11
Thanks for the bug report. This is the kind of thing we want to avoid with https://github.com/pantsbuild/pants/issues/7369

**Comment by jsirois** [comment] 2022-07-13 05:13
IIUC @chrisjrn will be taking over this area in the short term. I won't be around to have a look until July 22.

**Comment by benjyw** [comment] 2022-07-13 05:15
I'm unclear on why Python 3.9 was unavailable though

**Comment by jsirois** [comment] 2022-07-13 05:19
I know nothing about ASDF. I can see if I have time tomorrow to look in the am. Everything else aside, Pex works with ~any Python and it's been downloaded already. It's also Pants' smarts for finding Pythons; so that suggests an attack.

**Comment by jsirois** [comment] 2022-07-13 16:00
Trying to page this in, but noting fwict #110 was the 1st change to add asdf awareness to the script, and that was added by @ryanking who knows / uses asdf.

**Comment by benjyw** [comment] 2022-07-13 16:10
@kamalmarhubi In the second part of your repro, why is Python 3.9 no longer available?

**Comment by stephengaito** [comment] 2022-09-25 19:02
@benjyw unfortunately for PantsBuild, Ubunutu 22.04 (Jammy Jellyfish) installs Python 3.10.4 by default.... 

The whole point of asdf, for me, is to be able to have more modern Pythons than my default OS provides.

Having said this I can see that, at the moment, there is a hard dependency on older Pythons (in order to correctly embed Rust sub-systems, see: https://github.com/pantsbuild/pants/issues/7369).

SO for those who *do* use asdf... here is my *workaround* ...

1. install the most recent 3.9.x (or 3.8.x or even 3.7.x) versions of Python using asdf (see: https://www.python.org/downloads/ ). For example: 

>  `asdf install python 3.9.14`

2. in order to install pants for the ***first time*** ensure that your *global* `$HOME/.tool-versions` file selects the python version you just installed. (For example: `python 3.9.14` )
3. [now install pants as directed](https://www.pantsbuild.org/docs/installation)
4. now you need to ensure that any directory which contains the `./pants` script *also* has its own *local* `.tool-versions` file which selects the version of python required for pants (For example: `python 3.9.14`).
5. now that you have installed pants you can change your *global* `$HOME/.tool-versions` setting for python to what ever you want/need for your other work...
6. so long as you keep your current installation of pants ( located in `$HOME/.cache/pants` and `$HOME/.pex` ) any project which uses pants build should select the correct version of python for the needs of the pants builder.

I hope this helps.

**Comment by SimonBiggs** [comment] 2023-01-25 00:09
I was also able to fix the above by including the following file:

`.pants.bootstrap`
```env
PYTHON="$HOME/.asdf/installs/python/3.9.16/bin/python"
```

At the root of the monorepo.

However, this removes all sorts of flexibility, and I could not find how to write `$HOME/.asdf/installs/python/3.9.16/bin/python` into the `python-bootstrap.search_path` configuration item within `pants.toml`.

**Comment by benjyw** [comment] 2023-01-25 00:26
The good news is that https://github.com/pantsbuild/pants/issues/7369 has been completed, meaning that you can now install Pants with no interpreter at all (it embeds its own).

See here for how to install Pants the new way: https://www.pantsbuild.org/v2.15/docs/installation

**Comment by benjyw** [comment] 2023-01-25 00:26
So I think we can close this? Feel free to reopen if you think otherwise.

**Closed as completed by benjyw** 2023-01-25 00:26 UTC

**Comment by SimonBiggs** [comment] 2023-01-25 00:33
Oh amazing!

Thank you!

**Comment by SimonBiggs** [comment] 2023-01-25 00:35
> See here for how to install Pants the new way: https://www.pantsbuild.org/v2.15/docs/installation

Heads up, running:

```bash
/bin/bash -c "$(curl -fsSL https://static.pantsbuild.org/setup/pantsup.sh)" 
```

Gives the following:

```
$ /bin/bash -c "$(curl -fsSL https://static.pantsbuild.org/setup/pantsup.sh)" 
Downloading and installing the pants launcher ...
curl: (22) The requested URL returned error: 404
```

**Comment by benjyw** [comment] 2023-01-25 00:38
Do you have expired github creds in your ~/.netrc?

**Comment by benjyw** [comment] 2023-01-25 00:39
Oh, it's a 404, not a 401, so that wouldn't be a creds issue. 

Weird though, it works for me.

**Comment by SimonBiggs** [comment] 2023-01-25 01:03
Ah works now. Maybe a propagation issue?

**Comment by benjyw** [comment] 2023-01-25 02:03
🤷 :)

**Comment by SimonBiggs** [comment] 2023-01-25 03:20
I can confirm that it is working an absolute treat. Thank you! That is an amazing UX improvement :)
