### ISSUE TITLE
pants 1.21.0 setup failure when python 3.7 is installed but disabled via pyenv

### ISSUE THREAD

**Issue by zhanwu** [pantsbuild/setup#62] opened 2019-11-03 19:44 UTC
Pants version: 1.21.0
Pants installed via: `curl -L -O https://pantsbuild.github.io/setup/pants && chmod +x pants
`

Update the `pants.ini` to `pants_version: 1.21.0` then run `./pants`

```
C02XV41NJHD2:mlp-ark zhanwu.xiong$ ./pants
pyenv: python3.7: command not found

The `python3.7' command exists in these Python versions:
  3.7.4

pyenv: python3.7: command not found


The `python3.7' command exists in these Python versions:
  3.7.4

./pants: line 170: /Users/zhanwu.xiong/.cache/pants/setup/bootstrap-Darwin-x86_64/pants.35pSjk/install/bin/pip: No such file or directory
./pants: line 171: /Users/zhanwu.xiong/.cache/pants/setup/bootstrap-Darwin-x86_64/pants.35pSjk/install/bin/pip: No such file or directory
New virtual environment successfully created at /Users/zhanwu.xiong/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py.
./pants: line 193: /Users/zhanwu.xiong/.cache/pants/setup/bootstrap-Darwin-x86_64/1.21.0_py/bin/python: No such file or directory
```

Full `pants.ini` after update:
```
[GLOBAL]
pants_version: 1.21.0
print_exception_stacktrace: True

pythonpath: ["%(buildroot)s/plugins"]
plugins: [
    'pantsbuild.pants.contrib.go==%(pants_version)s',
    'pantsbuild.pants.contrib.python.checks==%(pants_version)s',
    'docker==4.0.2']

backend_packages : [
    'pants.backend.graph_info',
    'pants.backend.python',
    'pants.backend.native',
    'pants.backend.project_info',
    'pants.backend.codegen.grpcio.python',
    'pants.rules.core',
    'cruise.docker']

[python-setup]
interpreter_constraints: ["CPython>=3.6"]

[source]
source_root_patterns = ['src/python/*', 'src/*', 'src/main/*', 'src/scala/*', 'src/java/*']
# Per language reverse key map.
# Go lang is designed to be built from Monorepo structure
source_roots = {u'go/src': (u'go',), u'go/main/src': (u'go',)}

[python-repos]
indexes = ['https://artifactory.robot.car/artifactory/api/pypi/wheels-python-local/simple', 'https://pypi.org/simple/']
repos = []

[repl.py]
ipython = True

[go-distribution]
version: 1.12

[lint.python-eval]
skip: True
```

The immediate cause of the issue is pants setup believes `python3.7` is a valid python version, but actually it is not. See the demonstration below:

```
C02XV41NJHD2:mlp-ark zhanwu.xiong$ pyenv versions
  system
  2.7.15
* 3.6.9 (set by /Users/zhanwu.xiong/cruise/mlp-ark/.python-version)
  3.7.4

C02XV41NJHD2:mlp-ark zhanwu.xiong$ which python3.7
/Users/zhanwu.xiong/.pyenv/shims/python3.7

C02XV41NJHD2:mlp-ark zhanwu.xiong$ python3.7
pyenv: python3.7: command not found

The `python3.7' command exists in these Python versions:
  3.7.4
```

Arguably, this could be a `pyenv` issue

**Comment by tekumara** [comment] 2020-02-09 23:27
By design, the pyenv shim for `python3.7` will error when the active python environment is not the same major version (see https://github.com/pyenv/pyenv/issues/34)

If you switch to python 3.7 first, eg: `pyenv local  3.7.4` and then run pants, it should work.

**Comment by Eric-Arellano** [comment] 2020-02-22 17:16
This will be fixed by https://github.com/pantsbuild/setup/pull/66. Hope it helps!

Once that PR merges, you'll want to redownload the `./pants` script from https://raw.githubusercontent.com/pantsbuild/setup/gh-pages/pants as you must manually pull in any changes we make to the script.

**Closed as completed** 2020-02-22 17:39 UTC
